### ISSUE TITLE
Support for PHP 7.4

### ISSUE THREAD

**Issue by Braunson** [spatie/pest-plugin-test-time#1]
I tried leaving a Feature Request but got a 404 from GitHub since Discussions don't seem to be enabled in this repository.

Adding this to an existing project to build out some PEST tests but it requires PHP 8.x. No other PEST Plugin seem to have this requirement. Any way to support 7.4 - 8.0?

**Comment by freekmurze** [comment]
If you need PHP 7.4 support, feel free to fork the package 👍
